### PR TITLE
Publish to Gemfury

### PR DESCRIPTION
**Pull request by talyh**
Enables this package to be published to Gemfury.
Confirmed that it can be consumed.

### CODE REVIEW

**Comment by chrispang24** [comment]
@talyh - currently seeing no issues pulling from gemfury for this package, but can we update the published version on gemfury to pull latest changes on `master`?

There was a hotfix applied this week and can't test new API calls successfully on airflow without it: https://github.com/GoProperly/rets/pull/4.

**Comment by talyh** [comment]
currently seeing no issues pulling from gemfury for this package, but can we update the published version on gemfury to pull latest changes on `master`?


@chrispang24  - good to know it got consumed without a hitch
Can you try the version from Gemfury now?

**Comment by sktse** [comment]
FYI.... this is a reminder that this is *PUBLIC* repo

**Comment by talyh** [comment]
@sktse  - Thanks for the reminder.
Any concern about the content or effect of the PR with the consideration of this being public?
(Gemfury creds would still be needed for publishing  locally and CI will only publish on merged PRs)

**Comment by sktse** [comment]
@talyh 
> Any concern about the content or effect of the PR with the consideration of this being public?

Nope.  Pull request content looks good.
It is more of a reminder of what we are saying in the comments of PRs.

**Review by sktse — APPROVED** [review]

**Pull request merged**
